# Generated by Django 4.1 on 2022-08-25 01:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_items_meal_studentmeal_mealitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmeal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
